spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 248141281923-psmn883fggnsb8quks7unu2s7kahb7s8.apps.googleusercontent.com
            clientSecret: hug9NyytqTNUK5CMjEdDfA69
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.

    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect







#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 248141281923-psmn883fggnsb8quks7unu2s7kahb7s8.apps.googleusercontent.com
#            clientSecret: hug9NyytqTNUK5CMjEdDfA69
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - email
#              - profile
##  data:
##    mongodb:
##      uri: mongodb+srv://<EmployeeOnboarding>:<onboarding@123>@cluster0.pb6v3.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
##      database: EmployeeOnboarding
#
#app:
#  auth:
#    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
#    tokenExpirationMsec: 864000000
#  oauth2:
#    # After successfully authenticating with the OAuth2 Provider,
#    # we'll be generating an auth token for the user and sending the token to the
#    # redirectUri mentioned by the client in the /oauth2/authorize request.
#    # We're not using cookies because they won't work well in mobile clients.
#    authorizedRedirectUris:
#      - http://localhost:3000/oauth2/redirect
#      - myandroidapp://oauth2/redirect
#      - myiosapp://oauth2/redirect